service: moviesapi

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1

package:
  individually: true

functions:
  getallmovies:
    handler: MoviesApi::MoviesApi.GetAllFilmsHandler::Execute
    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: movies
          method: get
  getmoviebyid:
    handler: MoviesApi::MoviesApi.GetFilmByIdHandler::Execute2
    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: movies/{id}
          method: get
