service: moviesapi

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1

  apiName: movies-api # Use a custom name for the API Gateway API - needed to easily identify the resource
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:eu-central-1:403117364727:table/Movies"

package:
  # individually: true
  artifact: bin/release/net6.0/hello.zip


functions:
  GetAllMovies:
    handler: MoviesApi::MoviesApi.HandlersExample.GetAllMoviesHandler::ExecuteAsync
    events:
      - http:
          path: /movies
          method: GET

  GetMovieById:
    handler: MoviesApi::MoviesApi.HandlersExample.GetMovieByIdHandler::ExecuteAsync
    events:
      - http:
          path: /movies/{id}
          method: GET

  PutMovie:
    handler: MoviesApi::MoviesApi.HandlersExample.PutMovieHandler::ExecuteAsync
    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: movies
          method: POST
          authorizer:
            name: Authorizer
            resultTtlInSeconds: 60
            identitySource: method.request.header.Authorization
            identityValidationExpression: "Bearer.*" # regex to validate Authorization header quickly
            type: token

  Authorizer:
    handler: MoviesApi::MoviesApi.HandlersExample.AuthorizeHandler::Execute
    package:
      artifact: bin/release/net6.0/hello.zip

resources:
  Resources:
    # https://docs.aws.amazon.com/apigateway/latest/developerguide/supported-gateway-response-types.html
    # This is needed when access is denied by a custom Authorizer
    DefaultUnauthorizedResponse:
      DependsOn:
        - ApiGatewayRestApi
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseTemplates:
          application/json: |
            {
              "requestId": "$context.requestId",
              "errors": [
                { "description": $context.error.messageString }
              ]
            }
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: "401"

    # this thing is needed to process OPTIONS requests
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"

    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Movies
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
