service: moviesapi

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1

  apiName: movies-api # Use a custom name for the API Gateway API - needed to easily identify the resource
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:eu-central-1:403117364727:table/Movies"

package:
  individually: true

functions:
  GetAllMovies:
    handler: MoviesApi::MoviesApi.QueryMoviesHandler::GetAll
    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: movies
          method: GET
          cors: true # <-- CORS!

  GetMovieById:
    handler: MoviesApi::MoviesApi.QueryMoviesHandler::GetById
    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: movies/{id}
          method: GET
          cors: true # <-- CORS!

  PostMovieById:
    handler: MoviesApi::MoviesApi.CreateMovieHandler::ExecuteAsync
    package:
      artifact: bin/release/net6.0/hello.zip
    events:
      - http:
          path: movies
          method: POST
          cors: true # <-- CORS!
          authorizer:
            name: Authorizer
            resultTtlInSeconds: 5
            identitySource: method.request.header.Authorization
            identityValidationExpression: "Bearer.*" # regex to validate Authorization header quickly
            type: token

  Authorizer:
    handler: MoviesApi::MoviesApi.AuthorizeHandler::Execute
    package:
      artifact: bin/release/net6.0/hello.zip
      
resources:
  Resources:
    # this thing is required to process OPTIONS requests
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        StatusCode: '200'
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    # definition of DynamoDb table
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Movies
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
