@baseUrl = https://maphpn87xe.execute-api.eu-central-1.amazonaws.com/dev

GET {{baseUrl}}/movies HTTP/1.1

###
GET {{baseUrl}}/movies/1001 HTTP/1.1

###
OPTIONS  {{baseUrl}}/movies/1 HTTP/1.1

### Not Authorized POST request
POST {{baseUrl}}/movies HTTP/1.1
content-Type: application/json

{
  "Id": "100",
  "Title": "The Shawshank Redemption",
  "Description": "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
  "ReleaseDate": "1994-09-23",
  "Genre": "Drama",
  "Rating": 9.45
}

### Authorized POST request
POST {{baseUrl}}/movies HTTP/1.1
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsIm5ldyI6ImFkYXMifQ.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaXNzIjoic2V2byIsImlhdCI6MTUxNjIzOTAyMn0.7l5tVlWWwFfTwB8DwxWYkjf4sGL8Yqv8EGDcOEQrXfs

{
  "Id": "100",
  "Title": "The Shawshank Redemption",
  "Description": "Two imprisoned men bond over several years, finding solace and eventual redemption through acts of common decency.",
  "ReleaseDate": "1994-09-23",
  "Genre": "Drama",
  "Rating": 9.45
}

### Invalid POST request
POST {{baseUrl}}/movies
content-Type: application/json

{
  "Id": "2",
  "Description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
  "ReleaseDate": "1972-03-24",
  "Genre": "Crime, Drama",
  "Rating": 9.2
}