service: moviesapi

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:eu-central-1:403117364727:table/Movies"

package:
  individually: true

functions:
  RootServer:
    handler: MoviesApi.AspNetCoreServer
    url: true
    package:
      artifact: bin/release/net6.0/hello.zip
        
resources:
  Resources:
    MoviesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Movies
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
